<div align="center">

# MEGR7172/8172

### Computational Methods (Fall 2025)
### Duke 227, Tu/Th 08:30 - 09:45 pm

</div>

# 8. Linear Algebra 2


## 8.1 Systems of Linear Equations & Matrix Inverses

Solving systems of linear equations is a central application of linear algebra. Such systems can be written in matrix form as:

$$
A\mathbf{x} = \mathbf{b}
$$

where:
- $A$ is a matrix of coefficients,
- $\mathbf{x}$ is a column vector of variables,
- $\mathbf{b}$ is a column vector of constants.

### Methods for Solving $A\mathbf{x} = \mathbf{b}$

- **Matrix Inverse Method:** If $A$ is invertible, the solution is $\mathbf{x} = A^{-1}\mathbf{b}$.
- **Gaussian Elimination:** Systematically eliminates variables to reduce the system to row-echelon form, making it easier to solve.
- **LU Decomposition:** Factorizes $A$ into a lower triangular matrix $L$ and an upper triangular matrix $U$, so that $A = LU$. This simplifies solving multiple systems with the same $A$ but different $\mathbf{b}$.

### Is there a unique solution?

- **Unique Solution:** Exists if $A$ is square and invertible (i.e., $\det(A) \neq 0$).
- **No Solution:** Occurs if the system is inconsistent (e.g., parallel equations).
- **Infinite Solutions:** Occur if the system is underdetermined (more variables than independent equations).

**Summary Table:**

| Condition on $A$         | Solution Type         |
|--------------------------|----------------------|
| $\det(A) \neq 0$         | Unique solution      |
| $\det(A) = 0$, inconsistent | No solution      |
| $\det(A) = 0$, dependent    | Infinite solutions |

Understanding these concepts is crucial for applications in engineering, physics, computer science, and data analysis.

In [8]:
import numpy as np

# Example: Solving a system of linear equations using matrix inverse
# Coefficient matrix A and constant vector b
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])

# Solve for x using the inverse method: x = A^{-1}b
x = np.linalg.inv(A) @ b

print("Solution x:", x)
# This solves the system:
# 2x1 + x2 = 8
# x1 + 3x2 = 13

Solution x: [2.2 3.6]


In [9]:
# Gaussian Elimination Example

# System: 2x + y = 8, x + 3y = 13
# Augmented matrix:
# [2 1 | 8]
# [1 3 | 13]

# Step 1: Convert to upper triangular form
A_aug = np.array([[2., 1., 8.],
                  [1., 3., 13.]])

# Eliminate x from the second row
factor = A_aug[1,0] / A_aug[0,0]
A_aug[1] = A_aug[1] - factor * A_aug[0]

print("Upper triangular matrix after elimination:\n", A_aug)

# Step 2: Back substitution
y = A_aug[1,2] / A_aug[1,1]
x = (A_aug[0,2] - A_aug[0,1]*y) / A_aug[0,0]

print("Solution from Gaussian elimination: x =", x, ", y =", y)

Upper triangular matrix after elimination:
 [[2.  1.  8. ]
 [0.  2.5 9. ]]
Solution from Gaussian elimination: x = 2.2 , y = 3.6


In [10]:
# LU Decomposition Example
from scipy.linalg import lu

# Perform LU decomposition of matrix A
P, L, U = lu(A)

print("Matrix A:\n", A)
print("\nPermutation matrix P:\n", P)
print("\nLower triangular matrix L:\n", L)
print("\nUpper triangular matrix U:\n", U)

# Verify that PA = LU
print("\nCheck PA = LU:\n", np.allclose(P @ A, L @ U))

Matrix A:
 [[2 1]
 [1 3]]

Permutation matrix P:
 [[1. 0.]
 [0. 1.]]

Lower triangular matrix L:
 [[1.  0. ]
 [0.5 1. ]]

Upper triangular matrix U:
 [[2.  1. ]
 [0.  2.5]]

Check PA = LU:
 True


## 8.2 Matrix Diagonalization

Matrix diagonalization is a powerful technique in linear algebra that leverages eigenvalues and eigenvectors to simplify complex matrix operations.

### Diagonalization Using Eigenvalues and Eigenvectors

A square matrix $A$ is **diagonalizable** if it can be written as:
$$
A = PDP^{-1}
$$
where:
- $P$ is a matrix whose columns are the eigenvectors of $A$,
- $D$ is a diagonal matrix whose diagonal entries are the corresponding eigenvalues of $A$.

**Steps to Diagonalize a Matrix:**
1. **Find the eigenvalues** of $A$ by solving $\det(A - \lambda I) = 0$.
2. **Find the eigenvectors** for each eigenvalue by solving $(A - \lambda I)\mathbf{v} = 0$.
3. **Form matrix $P$** using the eigenvectors as columns.
4. **Form diagonal matrix $D$** with the eigenvalues on the diagonal.

### Why Diagonalization Matters

- **Matrix Powers:**  
    Diagonalization simplifies the computation of matrix powers:
    $$
    A^n = (PDP^{-1})^n = PD^nP^{-1}
    $$
    Since $D$ is diagonal, $D^n$ is easy to compute (just raise each diagonal entry to the $n$th power).

- **Solving Differential Equations:**  
    Systems of linear differential equations with constant coefficients can be solved efficiently by diagonalizing the coefficient matrix.

- **Applications:**  
    - Principal Component Analysis (PCA)
    - Quantum mechanics
    - Markov processes
    - Stability analysis in engineering

Diagonalization provides insight into the structure of a matrix and enables efficient computation in many scientific and engineering problems.

In [11]:
# Example: Diagonalization of a matrix

# Let's diagonalize matrix A
eigvals, eigvecs = np.linalg.eig(A)

print("Eigenvalues:\n", eigvals)
print("\nEigenvectors (columns):\n", eigvecs)

# Form the diagonal matrix D from eigenvalues
D = np.diag(eigvals)

# Form the matrix P from eigenvectors (columns)
P = eigvecs

# Compute P inverse
P_inv = np.linalg.inv(P)

# Check that A = P D P^{-1}
A_reconstructed = P @ D @ P_inv
print("\nReconstructed A from diagonalization:\n", A_reconstructed)
print("\nIs A approximately equal to P D P^{-1}?", np.allclose(A, A_reconstructed))

Eigenvalues:
 [1.38196601 3.61803399]

Eigenvectors (columns):
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]

Reconstructed A from diagonalization:
 [[2. 1.]
 [1. 3.]]

Is A approximately equal to P D P^{-1}? True


## Example: Diagonalizing a Matrix in a Real-World Application

Suppose we have a discrete-time population model for two interacting species, where the populations at time $n+1$ depend linearly on the populations at time $n$:

$$
\begin{bmatrix}
x_{n+1} \\
y_{n+1}
\end{bmatrix}
=
A
\begin{bmatrix}
x_n \\
y_n
\end{bmatrix}
$$

where $A = \begin{bmatrix} 2 & 1 \\ 1 & 3 \end{bmatrix}$ describes the interaction between the species.

### Step 1: Find Eigenvalues and Eigenvectors

We already computed the eigenvalues and eigenvectors of $A$ in the previous code cell.

### Step 2: Diagonalize $A$

Let $P$ be the matrix of eigenvectors and $D$ the diagonal matrix of eigenvalues. Then:

$$
A = PDP^{-1}
$$

### Step 3: Application — Predicting Future Populations

If the initial populations are $x_0$ and $y_0$, then after $n$ steps:

$$
\begin{bmatrix}
x_n \\
y_n
\end{bmatrix}
= A^n
\begin{bmatrix}
x_0 \\
y_0
\end{bmatrix}
= P D^n P^{-1}
\begin{bmatrix}
x_0 \\
y_0
\end{bmatrix}
$$

Diagonalization allows us to efficiently compute $A^n$ for large $n$, making it easy to predict long-term population dynamics.

---

**Summary:**  
Diagonalization transforms the problem of repeatedly multiplying by $A$ into simple multiplications by a diagonal matrix, which is computationally efficient and provides insight into the long-term behavior of the system (e.g., which population dominates as $n \to \infty$).